# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Scrudents' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'

  # Pods for Scrudents

  target 'ScrudentsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScrudentsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
